### ISSUE TITLE
Snatcher hangs on act2 after explosion in morgue

### ISSUE THREAD

**Issue by dbbgba** [krikzz/MEGA-PRO#1]
Basically exactly what is being described here: 
https://bitbucket.org/eke/genesis-plus-gx/issues/289/snatcher-hangs-after-explosion-in-morgue#:~:text=In%20Snatcher%2C%20when%20you%27re%20in%20the%20hospital%20morgue%2C,the%20emulated%20system%20is%20still%20reading%20the%20disc.

**Comment by krikzz** [comment]
Fix for this problem will be included in next OS update
